INSERT OR IGNORE INTO books (id, title, author, year, isbn) VALUES
(1,  'The Pragmatic Programmer',          'David Thomas, Andrew Hunt',    1999, 'ISBN-5705'),
(2,  'Clean Code',                        'Robert C. Martin',             2008, 'ISBN-5088'),
(3,  'Design Patterns',                   'Erich Gamma et al.',           1994, 'ISBN-3361'),
(4,  'Structure and Interpretation of Computer Programs', 'Harold Abelson, Gerald Jay Sussman', 1985, 'ISBN-1087'),
(5,  'The C Programming Language',        'Brian Kernighan, Dennis Ritchie', 1978, 'ISBN-0362'),
(6,  'Introduction to Algorithms',        'Thomas H. Cormen et al.',      2009, 'ISBN-3384'),
(7,  'Refactoring',                       'Martin Fowler',                2018, 'ISBN-5759'),
(8,  'Code Complete',                     'Steve McConnell',              2004, 'ISBN-1967'),
(9,  'The Mythical Man-Month',            'Frederick P. Brooks Jr.',     1975, 'ISBN-3595'),
(10, 'Effective Modern C++',              'Scott Meyers',                 2014, 'ISBN-0399'),
(11, 'C++ Primer',                        'Stanley B. Lippman',           2012, 'ISBN-1411'),
(12, 'Qt 6 Programming',                  'Mark Summerfield',             2023, NULL),
(13, 'Head First Design Patterns',        'Eric Freeman, Elisabeth Robson', 2020, 'ISBN-7800'),
(14, 'Working Effectively with Legacy Code', 'Michael Feathers',          2004, 'ISBN-7705'),
(15, 'Domain-Driven Design',              'Eric Evans',                   2003, 'ISBN-2521'),
(16, 'Algorithms',                        'Robert Sedgewick',             2011, 'ISBN-7351'),
(17, 'The Art of Computer Programming',   'Donald E. Knuth',              1968, 'ISBN-9683'),
(18, 'Compilers: Principles, Techniques, and Tools', 'Alfred V. Aho et al.', 2006, 'ISBN-8681'),
(19, 'Operating System Concepts',         'Abraham Silberschatz et al.',  2018, 'ISBN-2091'),
(20, 'Computer Networking: A Top-Down Approach', 'James Kurose, Keith Ross', 2016, 'ISBN-9414');
